version: "3.8"

services:
  scene_graph_benchmark:
    build:
      context: .  # Path to the Dockerfile
      dockerfile: Dockerfile
    image: scene_graph_benchmark_container
    runtime: nvidia  # Enables GPU support

    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - LD_LIBRARY_PATH=/usr/local/cuda/lib64
      - DEBIAN_FRONTEND=noninteractive

    env_file:
      - .env
      
    # Project directory structure reminder:
    # ------------------------------------------------------------------------------
    # Place the following files and folders in the same directory as this YAML file:
    # 
    # ├── docker-compose.yml     # This Docker Compose file.
    # ├── Dockerfile             # The Dockerfile used to build the container image.
    # ├── data/                  # Directory to store input datasets or files.
    # │   ├── ...                # (e.g., images, annotations, etc.)
    # ├── models/                # Directory to store machine learning models.
    # │   ├── ...                # (e.g., pre-trained models like .pth files.)
    # ├── output/                # Directory to store application outputs.
    # │   ├── ...                # (e.g., logs, predictions, or processed files.)
    # ------------------------------------------------------------------------------

    volumes:
      - ./data:/workspace/data
      - ./models:/workspace/models
      - ./output:/workspace/output
      - .:/lab_sg_extract  # Mount the project root directory for live development

    shm_size: "100GB"
    working_dir: /lab_sg_extract

    stdin_open: true
    tty: true
    command: [ "bash" ]